-- Drop tables (if they exist)
DROP TABLE IF EXISTS STORE_PAYOUTS;
DROP TABLE IF EXISTS PAYMENTS;
DROP TABLE IF EXISTS PURCHASE_VENDOR_MAPPING;
DROP TABLE IF EXISTS PURCHASE_ITEMS;
DROP TABLE IF EXISTS PURCHASES;
DROP TABLE IF EXISTS PROD_CAT;
DROP TABLE IF EXISTS PRODUCTS_CATEGORIES;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS STORES;
DROP TABLE IF EXISTS USERS;

-- Create USERS Table
CREATE TABLE USERS (
    USER_ID INT PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL,
    EMAIL NVARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARBINARY(MAX) NOT NULL,
    SALT NVARCHAR(50) NOT NULL,
    TELEPHONE NVARCHAR(15) CHECK (TELEPHONE LIKE '[0-9]%'),
    ADDRESS NVARCHAR(200) NOT NULL
);

-- Create STORES Table (with USER_ID as a foreign key)
CREATE TABLE STORES (
    STORE_ID INT PRIMARY KEY,
    STORE_NAME NVARCHAR(50) NOT NULL UNIQUE,
    EMAIL NVARCHAR(50) NOT NULL UNIQUE,
    IMAGE NVARCHAR(255),
    CATEGORY NVARCHAR(50),
    USER_ID INT NOT NULL,
    STRIPE_ID NVARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT FK_STORES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- Create PRODUCTS Table
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    STORE_ID INT NOT NULL,
    PRODUCT_NAME NVARCHAR(50) NOT NULL,
    DESCRIPTION NVARCHAR(200),
    IMAGE NVARCHAR(255),
    PRICE DECIMAL(10,2) NOT NULL,
    STOCK_QUANTITY INT NOT NULL,
    CONSTRAINT FK_PRODUCTS_STORES FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID) ON DELETE CASCADE
);

-- Create PRODUCTS_CATEGORIES Table
CREATE TABLE PRODUCTS_CATEGORIES (
    CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_NAME NVARCHAR(50) NOT NULL
);

-- Create PROD_CAT Table (Many-to-Many Relationship between PRODUCTS and PRODUCTS_CATEGORIES)
CREATE TABLE PROD_CAT (
    PRODUCT_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    PRIMARY KEY (PRODUCT_ID, CATEGORY_ID),
    CONSTRAINT FK_PROD_CAT_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PROD_CAT_CATEGORIES FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCTS_CATEGORIES(CATEGORY_ID) ON DELETE CASCADE
);

-- Create PURCHASES Table
CREATE TABLE PURCHASES (
    PURCHASE_ID INT PRIMARY KEY,
    USER_ID INT NOT NULL,
    TOTAL_PRICE DECIMAL(10,2) NOT NULL,
    PAYMENT_STATUS NVARCHAR(50) NOT NULL CHECK (PAYMENT_STATUS IN ('Pending', 'Completed', 'Failed')),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    STRIPE_SESSION_ID NVARCHAR(100),
    CONSTRAINT FK_PURCHASES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create PURCHASE_ITEMS Table
CREATE TABLE PURCHASE_ITEMS (
    PURCHASE_ITEM_ID INT PRIMARY KEY,
    PURCHASE_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE_AT_PURCHASE DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_PURCHASE_ITEMS_PURCHASES FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASES(PURCHASE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PURCHASE_ITEMS_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
);

-- Create PURCHASE_VENDOR_MAPPING Table
CREATE TABLE PURCHASE_VENDOR_MAPPING (
    PURCHASE_VENDOR_ID INT PRIMARY KEY,
    PURCHASE_ID INT NOT NULL,
    VENDOR_ID INT NOT NULL,
    VENDOR_AMOUNT DECIMAL(10,2) NOT NULL,
    CONSTRAINT FK_PURCHASE_VENDOR_MAPPING_PURCHASES FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASES(PURCHASE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PURCHASE_VENDOR_MAPPING_STORES FOREIGN KEY (VENDOR_ID) REFERENCES STORES(STORE_ID) ON DELETE CASCADE
);

-- Create PAYMENTS Table
CREATE TABLE PAYMENTS (
    PAYMENT_ID INT PRIMARY KEY,
    PURCHASE_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    PAYMENT_METHOD NVARCHAR(50) NOT NULL,
    TRANSACTION_ID NVARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    PAYMENT_DATE DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_PAYMENTS_PURCHASES FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASES(PURCHASE_ID),
    CONSTRAINT FK_PAYMENTS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create STORE_PAYOUTS Table
CREATE TABLE STORE_PAYOUTS (
    PAYOUT_ID INT PRIMARY KEY,
    STORE_ID INT NOT NULL,
    PURCHASE_ID INT NOT NULL,
    PAYOUT_AMOUNT DECIMAL(10,2) NOT NULL,
    PAYOUT_STATUS NVARCHAR(50) NOT NULL CHECK (PAYOUT_STATUS IN ('Pending', 'Paid', 'Failed')),
    PAYOUT_DATE DATETIME DEFAULT GETDATE(),
    PAYOUT_METHOD NVARCHAR(50),
    CONSTRAINT FK_STORE_PAYOUTS_STORES FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_STORE_PAYOUTS_PURCHASES FOREIGN KEY (PURCHASE_ID) REFERENCES PURCHASES(PURCHASE_ID) ON DELETE CASCADE
);